name: Deploy Bolão para o GitHub Pages

on:
  push:
    branches:
      - main # Dispara o deploy toda vez que você enviar algo para a branch main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/actions/setup-node@v4
        with:
          node-version: 20 # 💡 Corrigido aqui de node-size para node-version

      - name: Instalar Dependências e Gerar Build
        env:
          # 💡 Injeta os segredos salvos no painel do GitHub dentro do build do Vite
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        run: |
          npm install
          npm run build

      - name: Fazer o Deploy para o GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Pasta que o Vite gera
          branch: gh-pages # Branch de destino do site